Repository rhobs/rhobs-synthetics-agent, pull requests merged in 2025-08, with the labels that each got.

#13 Various prow related fixes
  .ci-operator.yaml
  go.mod
  go.sum
  internal/k8s/probe.go
  internal/k8s/probe_test.go
Labels: approved, lgtm

#19 SREP-804: Add Prometheus metrics for RHOBS Synthetics Agent
  deploy/template.yaml
  go.mod
  go.sum
  internal/agent/agent.go
  internal/agent/agent_test.go
  internal/agent/worker.go
  internal/metrics/metrics.go
  internal/metrics/metrics_test.go
  internal/version/version.go
  internal/version/version_test.go
  test/e2e/metrics_e2e_test.go
Labels: approved, jira/valid-reference, lgtm

#20 SREP-799: Add HTTP health endpoints for liveness and readiness checks
  internal/agent/agent.go
  internal/agent/agent_test.go
  internal/agent/worker.go
Labels: approved, jira/valid-reference, lgtm

#22 Add Agent PipelineRun Tekton configs
  .tekton/rhobs-synthetics-agent-main-pull-request.yaml
  .tekton/rhobs-synthetics-agent-main-push.yaml
Labels: approved, lgtm

#30 SREP-1201 Fix entrypoint.sh permissions and application name
  Dockerfile
  templates/template.yaml
Labels: approved

#31 Fix YAML syntax error in OpenShift template
  templates/template.yaml
Labels: approved

#29 Remove unused struct 'ResourceManager'
  internal/agent/agent.go
  internal/agent/agent_test.go
  internal/agent/worker.go
  internal/agent/worker_integration_test.go
  internal/agent/worker_test.go
Labels: approved, lgtm
